#
# $Id$
#
#
OBJ=adiosio.o 

LIBRARY=libadiosio.a

HEADER=

USES_BLAS=

#LIB_DEFINES = 

adiosio.o: adiosio.F90


include ../config/makefile.h
include ../config/makelib.h


#ifeq ($(USE_ADIOS2),y)
#  LIB_DEFINES += -DADIOS2
#endif
